[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.8"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.9.8"
volatile = "0.2.6 "
x86_64 = "0.15.1"
uart_16550 = "0.3.1"

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
# (0x10 << 1) | 1
test-success-exit-code = 33
# (in seconds)
test-timeout = 300

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false
